### ISSUE TITLE
What is the reason for this?    “fatal error: cvdraw/cvdraw.hpp:    ”

### ISSUE THREAD

**Issue by babatur** [rxdu/robosw#1]

**Comment by rxdu** [comment]
More details about your issue? And can you refer to the CI setup for building the code? It compiles without errors on my side.

**Comment by babatur** [comment]
Thank you for your reply.I just want to use the state_lattice module   only，I put the cvdraw and stopwatch  module into state_lattice module ,then no more missing files.but when I compile the program,When I compile the program：
[100%] Linking CXX executable /home/liu/local_plan/bvp/devel/lib/state_sample/test_state_lattice
/usr/bin/ld: 找不到 -lutilities
/usr/bin/ld: 找不到 -lmodel
/usr/bin/ld: 找不到 -llogging
/usr/bin/ld: 找不到 -lutilities
collect2: error: ld returned 1 exit status
state_sample/CMakeFiles/test_lattice_viz.dir/build.make:96: recipe for target '/home/liu/local_plan/bvp/devel/lib/state_sample/test_lattice_viz' failed
make[2]: *** [/home/liu/local_plan/bvp/devel/lib/state_sample/test_lattice_viz] Error 1

**Comment by babatur** [comment]
Thank you for your reply.I just want to use the state_lattice module only，I put the cvdraw and stopwatch module into state_lattice module ,then no more missing files.but when I compile the program,When I compile the program：
[100%] Linking CXX executable /home/liu/local_plan/bvp/devel/lib/state_sample/test_state_lattice
/usr/bin/ld: can't find -lutilities
/usr/bin/ld: can't find  -lmodel
/usr/bin/ld: can't find  -llogging
/usr/bin/ld: can't find  -lutilities
collect2: error: ld returned 1 exit status
state_sample/CMakeFiles/test_lattice_viz.dir/build.make:96: recipe for target '/home/liu/local_plan/bvp/devel/lib/state_sample/test_lattice_viz' failed
make[2]: *** [/home/liu/local_plan/bvp/devel/lib/state_sample/test_lattice_viz] Error 1

**Comment by rxdu** [comment]
I'm not sure if the "state_lattice" module would work as is, since the modules were taken from a different repo and were meant to be "cleaned up" before it can work again. So I would suggest you only use it as a reference implementation instead of using it directly.

**Comment by babatur** [comment]
Ok,thank you!!!
